'use client';
import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import SongCard from '../components/SongCard';
import GenreTag from '../components/GenreTag';
import { TRENDING_SONGS, GENRE_PRESETS } from '../lib/mockData';
import { getSongs, clearAllUserSongs } from '../lib/songStorage';
import { usePlayer } from '../context/PlayerContext';

export default function Home() {
  const { onPlaySong, currentSong, isPlaying } = usePlayer();
  const [selectedGenre, setSelectedGenre] = useState(null);
  const [userSongs, setUserSongs] = useState([]);

  const recentRowRef = useRef(null);
  const trendingRowRef = useRef(null);

  const scrollRow = (ref, dir) => {
    if (ref.current) {
      const amount = dir === 'left' ? -380 : 380;
      ref.current.scrollBy({ left: amount, behavior: 'smooth' });
    }
  };

  // Convert mouse wheel vertical scroll to horizontal row scroll
  const handleWheelScroll = (e) => {
    if (e.deltaY !== 0 && e.currentTarget) {
      e.currentTarget.scrollLeft += e.deltaY;
    }
  };

  useEffect(() => {
    setUserSongs(getSongs());
  }, []);

  const handleClearHistory = () => {
    clearAllUserSongs();
    setUserSongs([]);
  };

  const filteredTrending = selectedGenre
    ? TRENDING_SONGS.filter(
        (s) => s.genre.toLowerCase() === selectedGenre.name.toLowerCase()
      )
    : TRENDING_SONGS;

  return (
    <div className="home-page">
      {/* Hero Banner */}
      <section className="hero-banner glass-panel">
        <div className="hero-content">
          <div className="hero-badge">⚡ Suno-Powered AI Audio Workstation</div>
          <h1 className="hero-title">
            Make any song you can <span className="gradient-text">imagine</span>
          </h1>
          <p className="hero-subtitle">
            Describe a vibe, genre, or story. MONSTAH!!! Music AI instantly generates full songs, backing tracks, and lyrics in under 30 seconds.
          </p>
          <div className="hero-actions">
            <Link href="/create" className="glow-button hero-btn">
              <span>✨ Create New Song</span>
            </Link>
            <a href="#trending" className="secondary-btn">
              <span>🔥 Explore Trending</span>
            </a>
          </div>
        </div>
        <div className="hero-visual">
          <div className="floating-disc">
            <div className="disc-inner">🎵</div>
          </div>
        </div>
      </section>

      {/* User Recent Creations (if any) */}
      {userSongs.length > 0 && (
        <section className="feed-section">
          <div className="section-header">
            <div>
              <h2>Your Recent Generations</h2>
            </div>
            <div className="section-controls">
              <button
                className="scroll-btn-arrow"
                onClick={() => scrollRow(recentRowRef, 'left')}
                title="Scroll left"
              >
                ‹
              </button>
              <button
                className="scroll-btn-arrow"
                onClick={() => scrollRow(recentRowRef, 'right')}
                title="Scroll right"
              >
                ›
              </button>
              <button onClick={handleClearHistory} className="clear-hist-btn">
                🗑️ Clear
              </button>
              <Link href="/library" className="see-all-link">
                View All ({userSongs.length}) →
              </Link>
            </div>
          </div>
          <div className="horizontal-scroll-wrapper">
            <div
              className="songs-scroll-row"
              ref={recentRowRef}
              onWheel={handleWheelScroll}
            >
              {userSongs.map((song) => (
                <div key={song.id} className="scroll-card-item">
                  <SongCard
                    song={song}
                    isPlaying={isPlaying && currentSong?.id === song.id}
                    onPlay={(s) => onPlaySong(s, userSongs)}
                  />
                </div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Genre Filter & Trending Section */}
      <section className="feed-section" id="trending">
        <div className="section-header">
          <div>
            <h2>Trending Community Creations</h2>
            <span className="section-subtitle">Real tracks generated by music creators worldwide</span>
          </div>
          <div className="section-controls">
            <button
              className="scroll-btn-arrow"
              onClick={() => scrollRow(trendingRowRef, 'left')}
              title="Scroll left"
            >
              ‹
            </button>
            <button
              className="scroll-btn-arrow"
              onClick={() => scrollRow(trendingRowRef, 'right')}
              title="Scroll right"
            >
              ›
            </button>
          </div>
        </div>

        <div className="genres-scroll-bar">
          <button
            className={`all-genre-pill ${!selectedGenre ? 'active' : ''}`}
            onClick={() => setSelectedGenre(null)}
          >
            🔥 All Styles
          </button>
          {GENRE_PRESETS.map((genre) => (
            <GenreTag
              key={genre.name}
              genre={genre}
              isSelected={selectedGenre?.name === genre.name}
              onClick={(g) =>
                setSelectedGenre(selectedGenre?.name === g.name ? null : g)
              }
            />
          ))}
        </div>

        {/* Songs Horizontal Carousel */}
        <div className="horizontal-scroll-wrapper">
          <div
            className="songs-scroll-row"
            ref={trendingRowRef}
            onWheel={handleWheelScroll}
          >
            {filteredTrending.map((song) => (
              <div key={song.id} className="scroll-card-item">
                <SongCard
                  song={song}
                  isPlaying={isPlaying && currentSong?.id === song.id}
                  onPlay={(s) => onPlaySong(s, filteredTrending)}
                />
              </div>
            ))}
          </div>
        </div>
      </section>

      <style jsx>{`
        .home-page {
          padding: 32px 40px;
          display: flex;
          flex-direction: column;
          gap: 40px;
        }

        .hero-banner {
          border-radius: var(--radius-lg);
          padding: 48px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          position: relative;
          overflow: hidden;
          background: linear-gradient(135deg, rgba(124, 58, 237, 0.25) 0%, rgba(236, 72, 153, 0.15) 100%),
                      var(--bg-glass);
          border: 1px solid rgba(124, 58, 237, 0.3);
        }

        .hero-content {
          max-width: 600px;
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .hero-badge {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          padding: 6px 14px;
          border-radius: var(--radius-full);
          background: rgba(124, 58, 237, 0.2);
          border: 1px solid var(--accent-purple);
          font-size: 12px;
          font-weight: 600;
          color: var(--accent-pink);
          width: fit-content;
        }

        .hero-title {
          font-family: var(--font-heading);
          font-size: 42px;
          font-weight: 900;
          line-height: 1.15;
          letter-spacing: -0.5px;
        }

        .gradient-text {
          background: var(--gradient-primary);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .hero-subtitle {
          font-size: 16px;
          color: var(--text-secondary);
          line-height: 1.6;
        }

        .hero-actions {
          display: flex;
          align-items: center;
          gap: 16px;
          margin-top: 8px;
        }

        :global(.hero-btn) {
          padding: 14px 32px;
          font-size: 16px;
        }

        .secondary-btn {
          padding: 14px 24px;
          border-radius: var(--radius-full);
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid var(--border-color);
          color: var(--text-primary);
          font-size: 15px;
          font-weight: 600;
          transition: all 0.2s ease;
        }

        .secondary-btn:hover {
          background: rgba(255, 255, 255, 0.1);
          transform: translateY(-2px);
        }

        .hero-visual {
          display: flex;
          align-items: center;
          justify-content: center;
          padding-right: 20px;
        }

        .floating-disc {
          width: 140px;
          height: 140px;
          border-radius: 50%;
          background: var(--gradient-primary);
          padding: 4px;
          box-shadow: 0 0 50px var(--accent-purple-glow);
          animation: spinSlow 12s linear infinite;
        }

        .disc-inner {
          width: 100%;
          height: 100%;
          border-radius: 50%;
          background: var(--bg-primary);
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 48px;
        }

        .feed-section {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }

        .section-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-wrap: wrap;
          gap: 12px;
        }

        .section-header h2 {
          font-family: var(--font-heading);
          font-size: 24px;
          font-weight: 800;
        }

        .section-subtitle {
          font-size: 14px;
          color: var(--text-muted);
          display: block;
          margin-top: 2px;
        }

        .section-controls {
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .scroll-btn-arrow {
          width: 36px;
          height: 36px;
          border-radius: 50%;
          background: rgba(255, 255, 255, 0.06);
          border: 1px solid var(--border-color);
          color: var(--text-primary);
          font-size: 20px;
          display: flex;
          align-items: center;
          justify-content: center;
          transition: all 0.2s ease;
          line-height: 1;
        }

        .scroll-btn-arrow:hover {
          background: var(--gradient-primary);
          border-color: transparent;
          transform: scale(1.08);
          box-shadow: 0 4px 14px var(--accent-purple-glow);
        }

        .clear-hist-btn {
          background: rgba(239, 68, 68, 0.15);
          border: 1px solid rgba(239, 68, 68, 0.4);
          color: #fca5a5;
          padding: 6px 12px;
          border-radius: var(--radius-full);
          font-size: 12px;
          font-weight: 600;
          transition: background 0.2s ease;
        }

        .clear-hist-btn:hover {
          background: rgba(239, 68, 68, 0.25);
        }

        .see-all-link {
          font-size: 14px;
          color: var(--accent-pink);
          font-weight: 600;
        }

        .see-all-link:hover {
          text-decoration: underline;
        }

        .genres-scroll-bar {
          display: flex;
          align-items: center;
          gap: 10px;
          overflow-x: auto;
          padding-bottom: 8px;
        }

        .all-genre-pill {
          padding: 8px 18px;
          border-radius: var(--radius-full);
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid var(--border-color);
          color: var(--text-secondary);
          font-size: 13px;
          font-weight: 600;
          white-space: nowrap;
          transition: all 0.2s ease;
        }

        .all-genre-pill.active {
          color: #fff;
          background: var(--gradient-primary);
          border-color: transparent;
        }

        .horizontal-scroll-wrapper {
          position: relative;
          width: 100%;
          max-width: 100%;
        }

        .songs-scroll-row {
          display: flex;
          gap: 20px;
          overflow-x: scroll !important;
          overflow-y: hidden;
          scroll-behavior: smooth;
          padding-bottom: 16px;
          padding-top: 6px;
          width: 100%;
          max-width: 100%;
          box-sizing: border-box;
          -webkit-overflow-scrolling: touch;
          scrollbar-width: auto !important;
          scrollbar-color: rgba(124, 58, 237, 0.7) rgba(255, 255, 255, 0.08) !important;
        }

        .songs-scroll-row::-webkit-scrollbar {
          height: 10px !important;
          display: block !important;
        }

        .songs-scroll-row::-webkit-scrollbar-track {
          background: rgba(255, 255, 255, 0.06) !important;
          border-radius: var(--radius-full);
          margin: 0 4px;
        }

        .songs-scroll-row::-webkit-scrollbar-thumb {
          background: var(--accent-purple) !important;
          border-radius: var(--radius-full);
          border: 2px solid rgba(18, 18, 28, 0.8);
        }

        .songs-scroll-row::-webkit-scrollbar-thumb:hover {
          background: var(--accent-pink) !important;
        }

        .scroll-card-item {
          flex: 0 0 290px;
          min-width: 290px;
          max-width: 290px;
        }
      `}</style>
    </div>
  );
}
