'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import SongCard from '../components/SongCard';
import GenreTag from '../components/GenreTag';
import { TRENDING_SONGS, GENRE_PRESETS } from '../lib/mockData';
import { getSongs, clearAllUserSongs } from '../lib/songStorage';
import { usePlayer } from '../context/PlayerContext';

export default function Home() {
  const { onPlaySong, currentSong, isPlaying } = usePlayer();
  const [selectedGenre, setSelectedGenre] = useState(null);
  const [userSongs, setUserSongs] = useState([]);

  useEffect(() => {
    setUserSongs(getSongs());
  }, []);

  const handleClearHistory = () => {
    clearAllUserSongs();
    setUserSongs([]);
  };

  const filteredTrending = selectedGenre
    ? TRENDING_SONGS.filter(
        (s) => s.genre.toLowerCase() === selectedGenre.name.toLowerCase()
      )
    : TRENDING_SONGS;

  return (
    <div className="home-page">
      {/* Hero Banner */}
      <section className="hero-banner glass-panel">
        <div className="hero-content">
          <div className="hero-badge">⚡ Suno-Powered AI Audio Workstation</div>
          <h1 className="hero-title">
            Make any song you can <span className="gradient-text">imagine</span>
          </h1>
          <p className="hero-subtitle">
            Describe a vibe, genre, or story. MONSTAH!!! Music AI instantly generates full songs, backing tracks, and lyrics in under 30 seconds.
          </p>
          <div className="hero-actions">
            <Link href="/create" className="glow-button hero-btn">
              <span>✨ Create New Song</span>
            </Link>
            <a href="#trending" className="secondary-btn">
              <span>🔥 Explore Trending</span>
            </a>
          </div>
        </div>
        <div className="hero-visual">
          <div className="floating-disc">
            <div className="disc-inner">🎵</div>
          </div>
        </div>
      </section>

      {/* User Recent Creations (if any) */}
      {userSongs.length > 0 && (
        <section className="feed-section">
          <div className="section-header">
            <h2>Your Recent Generations</h2>
            <div style={{ display: 'flex', gap: '14px', alignItems: 'center' }}>
              <button
                onClick={handleClearHistory}
                style={{
                  background: 'rgba(239, 68, 68, 0.15)',
                  border: '1px solid rgba(239, 68, 68, 0.4)',
                  color: '#fca5a5',
                  padding: '4px 12px',
                  borderRadius: '12px',
                  fontSize: '12px',
                  fontWeight: '600',
                  cursor: 'pointer',
                }}
              >
                🗑️ Clear History
              </button>
              <Link href="/library" className="see-all-link">
                View All ({userSongs.length}) →
              </Link>
            </div>
          </div>
          <div className="songs-grid">
            {userSongs.slice(0, 3).map((song) => (
              <SongCard
                key={song.id}
                song={song}
                isPlaying={isPlaying && currentSong?.id === song.id}
                onPlay={(s) => onPlaySong(s, userSongs)}
              />
            ))}
          </div>
        </section>
      )}

      {/* Genre Filter Bar */}
      <section className="feed-section" id="trending">
        <div className="section-header">
          <h2>Trending Community Creations</h2>
          <span className="section-subtitle">Real tracks generated by music creators worldwide</span>
        </div>

        <div className="genres-scroll-bar">
          <button
            className={`all-genre-pill ${!selectedGenre ? 'active' : ''}`}
            onClick={() => setSelectedGenre(null)}
          >
            🔥 All Styles
          </button>
          {GENRE_PRESETS.map((genre) => (
            <GenreTag
              key={genre.name}
              genre={genre}
              isSelected={selectedGenre?.name === genre.name}
              onClick={(g) =>
                setSelectedGenre(selectedGenre?.name === g.name ? null : g)
              }
            />
          ))}
        </div>

        {/* Songs Grid */}
        <div className="songs-grid">
          {filteredTrending.map((song) => (
            <SongCard
              key={song.id}
              song={song}
              isPlaying={isPlaying && currentSong?.id === song.id}
              onPlay={(s) => onPlaySong(s, filteredTrending)}
            />
          ))}
        </div>
      </section>

      <style jsx>{`
        .home-page {
          padding: 32px 40px;
          display: flex;
          flex-direction: column;
          gap: 40px;
        }

        .hero-banner {
          border-radius: var(--radius-lg);
          padding: 48px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          position: relative;
          overflow: hidden;
          background: linear-gradient(135deg, rgba(124, 58, 237, 0.25) 0%, rgba(236, 72, 153, 0.15) 100%),
                      var(--bg-glass);
          border: 1px solid rgba(124, 58, 237, 0.3);
        }

        .hero-content {
          max-width: 600px;
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .hero-badge {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          padding: 6px 14px;
          border-radius: var(--radius-full);
          background: rgba(124, 58, 237, 0.2);
          border: 1px solid var(--accent-purple);
          font-size: 12px;
          font-weight: 600;
          color: var(--accent-pink);
          width: fit-content;
        }

        .hero-title {
          font-family: var(--font-heading);
          font-size: 42px;
          font-weight: 900;
          line-height: 1.15;
          letter-spacing: -0.5px;
        }

        .gradient-text {
          background: var(--gradient-primary);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .hero-subtitle {
          font-size: 16px;
          color: var(--text-secondary);
          line-height: 1.6;
        }

        .hero-actions {
          display: flex;
          align-items: center;
          gap: 16px;
          margin-top: 8px;
        }

        :global(.hero-btn) {
          padding: 14px 32px;
          font-size: 16px;
        }

        .secondary-btn {
          padding: 14px 24px;
          border-radius: var(--radius-full);
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid var(--border-color);
          color: var(--text-primary);
          font-size: 15px;
          font-weight: 600;
          transition: all 0.2s ease;
        }

        .secondary-btn:hover {
          background: rgba(255, 255, 255, 0.1);
          transform: translateY(-2px);
        }

        .hero-visual {
          display: flex;
          align-items: center;
          justify-content: center;
          padding-right: 20px;
        }

        .floating-disc {
          width: 140px;
          height: 140px;
          border-radius: 50%;
          background: var(--gradient-primary);
          padding: 4px;
          box-shadow: 0 0 50px var(--accent-purple-glow);
          animation: spinSlow 12s linear infinite;
        }

        .disc-inner {
          width: 100%;
          height: 100%;
          border-radius: 50%;
          background: var(--bg-primary);
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 48px;
        }

        .feed-section {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }

        .section-header {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
        }

        .section-header h2 {
          font-family: var(--font-heading);
          font-size: 24px;
          font-weight: 800;
        }

        .section-subtitle {
          font-size: 14px;
          color: var(--text-muted);
        }

        .see-all-link {
          font-size: 14px;
          color: var(--accent-pink);
          font-weight: 600;
        }

        .see-all-link:hover {
          text-decoration: underline;
        }

        .genres-scroll-bar {
          display: flex;
          align-items: center;
          gap: 10px;
          overflow-x: auto;
          padding-bottom: 8px;
        }

        .all-genre-pill {
          padding: 8px 18px;
          border-radius: var(--radius-full);
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid var(--border-color);
          color: var(--text-secondary);
          font-size: 13px;
          font-weight: 600;
          white-space: nowrap;
          transition: all 0.2s ease;
        }

        .all-genre-pill.active {
          color: #fff;
          background: var(--gradient-primary);
          border-color: transparent;
        }

        .songs-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
          gap: 24px;
        }
      `}</style>
    </div>
  );
}
