// Seeded mock data for the Explore/Trending feed
// Using local static demo tracks for 100% reliable audio playback
const SAMPLE_TRACKS = [
  '/demo-audio/synthwave.mp3',
  '/demo-audio/lofi.mp3',
  '/demo-audio/edm.mp3',
  '/demo-audio/jazz.mp3',
  '/demo-audio/indie.mp3',
  '/demo-audio/orchestral.mp3',
];

export const TRENDING_SONGS = [
  {
    id: 'mock_1',
    title: 'Neon Runaway',
    prompt: 'synthwave cyberpunk chase scene at night',
    genre: 'Synthwave',
    mood: 'energetic',
    duration: 25,
    plays: 84200,
    likes: 3100,
    createdAt: '2024-10-01T10:00:00Z',
    audioUrl: '/demo-audio/synthwave.mp3',
    vocalUrl: null,
    hasVocals: false,
    coverGradient: 'linear-gradient(135deg, #7c3aed 0%, #2563eb 100%)',
    lyrics: {
      title: 'Neon Runaway',
      lyrics: `[Verse 1]\nNeon lights paint the asphalt rain\nEngine roars through the midnight lane\nCity blurs in a streak of light\nRunning hard through the electric night\n\n[Chorus]\nNeon runaway, can't slow me down\nBurning rubber through this neon town\nNeon runaway, the grid is on fire\nPushing limits, climbing ever higher\n\n[Verse 2]\nRooftops flash in the rearview glass\nEvery second's gone before it's passed\nCircuits hum in the city's veins\nWe were built to break our chains\n\n[Outro]\nNeon runaway...`,
    },
    isMock: true,
    userName: 'CyberSynth',
    userAvatar: '🤖',
  },
  {
    id: 'mock_2',
    title: 'Golden Hour Drift',
    prompt: 'lo-fi hip hop chill study beats warm afternoon',
    genre: 'Lo-Fi',
    mood: 'mellow',
    duration: 25,
    plays: 127800,
    likes: 5620,
    createdAt: '2024-10-02T14:00:00Z',
    audioUrl: '/demo-audio/lofi.mp3',
    vocalUrl: null,
    hasVocals: false,
    coverGradient: 'linear-gradient(135deg, #f59e0b 0%, #ec4899 100%)',
    lyrics: {
      title: 'Golden Hour Drift',
      lyrics: `[Verse 1]\nDust motes float in the afternoon sun\nTea gone cold, but I'm not done\nPages turn with a lazy pace\nLost in thought in this quiet space\n\n[Chorus]\nGolden hour drift, fade away\nEverything can wait today\nGolden hour drift, soft and slow\nWatch the amber embers glow\n\n[Bridge]\nTime is a river, I'm just a leaf\nCarried gently to sweet relief\n\n[Outro]\nGolden hour... drift...`,
    },
    isMock: true,
    userName: 'LoFiLens',
    userAvatar: '☕',
  },
  {
    id: 'mock_3',
    title: 'Bass Drop Protocol',
    prompt: 'hard hitting EDM festival drop massive bass',
    genre: 'EDM',
    mood: 'euphoric',
    duration: 25,
    plays: 203400,
    likes: 9870,
    createdAt: '2024-10-03T20:00:00Z',
    audioUrl: '/demo-audio/edm.mp3',
    vocalUrl: null,
    hasVocals: false,
    coverGradient: 'linear-gradient(135deg, #06b6d4 0%, #7c3aed 100%)',
    lyrics: {
      title: 'Bass Drop Protocol',
      lyrics: `[Build Up]\nFrequencies rising, the crowd is alive\nEvery heartbeat locked into the drive\nCountdown starting, three... two... one...\n\n[Drop]\nBASS DROP PROTOCOL — the floor explodes\nSonic overload, the system overflows\nBass drop protocol — we own the night\nThousand hands in the air, bathed in light\n\n[Breakdown]\nBreathing in... the silence before the storm\nOne last moment... before we transform\n\n[Final Drop]\nBASS DROP PROTOCOL!`,
    },
    isMock: true,
    userName: 'DropMaster',
    userAvatar: '⚡',
  },
  {
    id: 'mock_4',
    title: 'Midnight Jazz Club',
    prompt: 'smooth jazz saxophone late night intimate bar',
    genre: 'Jazz',
    mood: 'melancholic',
    duration: 25,
    plays: 61300,
    likes: 2890,
    createdAt: '2024-10-04T23:00:00Z',
    audioUrl: '/demo-audio/jazz.mp3',
    vocalUrl: null,
    hasVocals: false,
    coverGradient: 'linear-gradient(135deg, #1a1a2e 0%, #b45309 100%)',
    lyrics: {
      title: 'Midnight Jazz Club',
      lyrics: `[Verse 1]\nSmoke curls slow by the velvet booth\nSaxophone singing of something like truth\nIce clinks cold in a crystal glass\nMidnight moments that fade too fast\n\n[Chorus]\nMidnight jazz club, low and blue\nEvery note that I play's for you\nMidnight jazz club, hazy air\nWishing you were still sitting there\n\n[Outro]\nOne more song as the crowd thins out\nJust the music knows what love's about...`,
    },
    isMock: true,
    userName: 'NightOwlBop',
    userAvatar: '🎷',
  },
  {
    id: 'mock_5',
    title: 'Solar Flare',
    prompt: 'upbeat indie pop summer road trip carefree',
    genre: 'Indie',
    mood: 'uplifting',
    duration: 25,
    plays: 155600,
    likes: 7200,
    createdAt: '2024-10-05T12:00:00Z',
    audioUrl: '/demo-audio/indie.mp3',
    vocalUrl: null,
    hasVocals: false,
    coverGradient: 'linear-gradient(135deg, #10b981 0%, #f59e0b 100%)',
    lyrics: {
      title: 'Solar Flare',
      lyrics: `[Verse 1]\nWindows down on the open road\nLeft behind every heavy load\nSunflower fields on either side\nNothing but blue sky for the ride\n\n[Chorus]\nSolar flare, burn right through me\nSolar flare, finally free\nEvery mile a revelation\nThis is my emancipation\n\n[Verse 2]\nRadio finds our favourite song\nSinging loud, can't do it wrong\nGasoline and possibility\nThis is what it means to be\n\n[Outro]\nSolar flare, burning bright...`,
    },
    isMock: true,
    userName: 'SunChaser',
    userAvatar: '🌻',
  },
  {
    id: 'mock_6',
    title: 'Ancient Stone',
    prompt: 'epic orchestral cinematic fantasy battle',
    genre: 'Orchestral',
    mood: 'intense',
    duration: 25,
    plays: 98700,
    likes: 4350,
    createdAt: '2024-10-06T08:00:00Z',
    audioUrl: '/demo-audio/orchestral.mp3',
    vocalUrl: null,
    hasVocals: false,
    coverGradient: 'linear-gradient(135deg, #dc2626 0%, #1e1b4b 100%)',
    lyrics: {
      title: 'Ancient Stone',
      lyrics: `[Intro — Choir]\nFrom the depths of ancient stone\nWarriors rise to claim their throne\n\n[Verse 1]\nThunder rolls across the field\nIron swords and iron will\nFlags of fallen kingdoms fly\nBeneath a bruised and bleeding sky\n\n[Chorus — Epic]\nANCIENT STONE, ANCIENT BONE\nEvery hero fights alone\nANCIENT STONE, rise and fall\nLegends etched upon the wall\n\n[Outro — Fading Choir]\nAncient stone... remember all...`,
    },
    isMock: true,
    userName: 'EpicForge',
    userAvatar: '⚔️',
  },
];

export const GENRE_PRESETS = [
  { name: 'Pop', emoji: '🎤', prompt: 'upbeat catchy pop song with modern production', color: '#ec4899' },
  { name: 'Hip-Hop', emoji: '🎧', prompt: 'hard hitting hip hop with deep bass and sharp snares', color: '#f59e0b' },
  { name: 'Rap', emoji: '🎤', prompt: 'fast paced rap with punchy 808s aggressive delivery and hard hitting lyrics', color: '#ef4444' },
  { name: 'EDM', emoji: '⚡', prompt: 'euphoric EDM drop with massive bassline and synths', color: '#06b6d4' },
  { name: 'Lo-Fi', emoji: '☕', prompt: 'chill lo-fi chillout study beats warm vinyl tape', color: '#10b981' },
  { name: 'Jazz', emoji: '🎷', prompt: 'smooth jazz with saxophone piano and brushed drums', color: '#b45309' },
  { name: 'Rock', emoji: '🎸', prompt: 'powerful rock with distorted guitars and driving drums', color: '#dc2626' },
  { name: 'Synthwave', emoji: '🌆', prompt: 'retro 80s synthwave with pulsing bassline and arpeggios', color: '#7c3aed' },
  { name: 'Indie', emoji: '🌻', prompt: 'indie pop with jangly guitar vocals and breezy feel', color: '#16a34a' },
  { name: 'Classical', emoji: '🎻', prompt: 'dramatic orchestral classical strings and piano', color: '#6366f1' },
  { name: 'R&B', emoji: '💜', prompt: 'smooth R&B groove with silky production and soul', color: '#9333ea' },
  { name: 'Metal', emoji: '🤘', prompt: 'heavy metal with blast beats shredding guitar and power', color: '#374151' },
  { name: 'Ambient', emoji: '🌌', prompt: 'atmospheric ambient soundscape dreamy and ethereal', color: '#0891b2' },
];
